// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPluginsNetboxDNSRecordsBulkDeleteParams creates a new PluginsNetboxDNSRecordsBulkDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSRecordsBulkDeleteParams() *PluginsNetboxDNSRecordsBulkDeleteParams {
	return &PluginsNetboxDNSRecordsBulkDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSRecordsBulkDeleteParamsWithTimeout creates a new PluginsNetboxDNSRecordsBulkDeleteParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSRecordsBulkDeleteParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSRecordsBulkDeleteParams {
	return &PluginsNetboxDNSRecordsBulkDeleteParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSRecordsBulkDeleteParamsWithContext creates a new PluginsNetboxDNSRecordsBulkDeleteParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSRecordsBulkDeleteParamsWithContext(ctx context.Context) *PluginsNetboxDNSRecordsBulkDeleteParams {
	return &PluginsNetboxDNSRecordsBulkDeleteParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSRecordsBulkDeleteParamsWithHTTPClient creates a new PluginsNetboxDNSRecordsBulkDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSRecordsBulkDeleteParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSRecordsBulkDeleteParams {
	return &PluginsNetboxDNSRecordsBulkDeleteParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSRecordsBulkDeleteParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns records bulk delete operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSRecordsBulkDeleteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns records bulk delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) WithDefaults() *PluginsNetboxDNSRecordsBulkDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns records bulk delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns records bulk delete params
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSRecordsBulkDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns records bulk delete params
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns records bulk delete params
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) WithContext(ctx context.Context) *PluginsNetboxDNSRecordsBulkDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns records bulk delete params
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns records bulk delete params
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSRecordsBulkDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns records bulk delete params
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSRecordsBulkDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
