// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSZonesNameserversReader is a Reader for the PluginsNetboxDNSZonesNameservers structure.
type PluginsNetboxDNSZonesNameserversReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSZonesNameserversReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSZonesNameserversOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSZonesNameserversDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSZonesNameserversOK creates a PluginsNetboxDNSZonesNameserversOK with default headers values
func NewPluginsNetboxDNSZonesNameserversOK() *PluginsNetboxDNSZonesNameserversOK {
	return &PluginsNetboxDNSZonesNameserversOK{}
}

/*
PluginsNetboxDNSZonesNameserversOK describes a response with status code 200, with default header values.

PluginsNetboxDNSZonesNameserversOK plugins netbox Dns zones nameservers o k
*/
type PluginsNetboxDNSZonesNameserversOK struct {
	Payload *models.Zone
}

// IsSuccess returns true when this plugins netbox Dns zones nameservers o k response has a 2xx status code
func (o *PluginsNetboxDNSZonesNameserversOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns zones nameservers o k response has a 3xx status code
func (o *PluginsNetboxDNSZonesNameserversOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns zones nameservers o k response has a 4xx status code
func (o *PluginsNetboxDNSZonesNameserversOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns zones nameservers o k response has a 5xx status code
func (o *PluginsNetboxDNSZonesNameserversOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns zones nameservers o k response a status code equal to that given
func (o *PluginsNetboxDNSZonesNameserversOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns zones nameservers o k response
func (o *PluginsNetboxDNSZonesNameserversOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSZonesNameserversOK) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/nameservers/][%d] pluginsNetboxDnsZonesNameserversOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSZonesNameserversOK) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/nameservers/][%d] pluginsNetboxDnsZonesNameserversOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSZonesNameserversOK) GetPayload() *models.Zone {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesNameserversOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSZonesNameserversDefault creates a PluginsNetboxDNSZonesNameserversDefault with default headers values
func NewPluginsNetboxDNSZonesNameserversDefault(code int) *PluginsNetboxDNSZonesNameserversDefault {
	return &PluginsNetboxDNSZonesNameserversDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSZonesNameserversDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSZonesNameserversDefault plugins netbox dns zones nameservers default
*/
type PluginsNetboxDNSZonesNameserversDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns zones nameservers default response has a 2xx status code
func (o *PluginsNetboxDNSZonesNameserversDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns zones nameservers default response has a 3xx status code
func (o *PluginsNetboxDNSZonesNameserversDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns zones nameservers default response has a 4xx status code
func (o *PluginsNetboxDNSZonesNameserversDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns zones nameservers default response has a 5xx status code
func (o *PluginsNetboxDNSZonesNameserversDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns zones nameservers default response a status code equal to that given
func (o *PluginsNetboxDNSZonesNameserversDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns zones nameservers default response
func (o *PluginsNetboxDNSZonesNameserversDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSZonesNameserversDefault) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/nameservers/][%d] plugins_netbox-dns_zones_nameservers default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesNameserversDefault) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/nameservers/][%d] plugins_netbox-dns_zones_nameservers default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesNameserversDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesNameserversDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
