// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PluginsNetboxDNSRecordsDeleteReader is a Reader for the PluginsNetboxDNSRecordsDelete structure.
type PluginsNetboxDNSRecordsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSRecordsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPluginsNetboxDNSRecordsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSRecordsDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSRecordsDeleteNoContent creates a PluginsNetboxDNSRecordsDeleteNoContent with default headers values
func NewPluginsNetboxDNSRecordsDeleteNoContent() *PluginsNetboxDNSRecordsDeleteNoContent {
	return &PluginsNetboxDNSRecordsDeleteNoContent{}
}

/*
PluginsNetboxDNSRecordsDeleteNoContent describes a response with status code 204, with default header values.

PluginsNetboxDNSRecordsDeleteNoContent plugins netbox Dns records delete no content
*/
type PluginsNetboxDNSRecordsDeleteNoContent struct {
}

// IsSuccess returns true when this plugins netbox Dns records delete no content response has a 2xx status code
func (o *PluginsNetboxDNSRecordsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns records delete no content response has a 3xx status code
func (o *PluginsNetboxDNSRecordsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns records delete no content response has a 4xx status code
func (o *PluginsNetboxDNSRecordsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns records delete no content response has a 5xx status code
func (o *PluginsNetboxDNSRecordsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns records delete no content response a status code equal to that given
func (o *PluginsNetboxDNSRecordsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the plugins netbox Dns records delete no content response
func (o *PluginsNetboxDNSRecordsDeleteNoContent) Code() int {
	return 204
}

func (o *PluginsNetboxDNSRecordsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/records/{id}/][%d] pluginsNetboxDnsRecordsDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSRecordsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/records/{id}/][%d] pluginsNetboxDnsRecordsDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSRecordsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPluginsNetboxDNSRecordsDeleteDefault creates a PluginsNetboxDNSRecordsDeleteDefault with default headers values
func NewPluginsNetboxDNSRecordsDeleteDefault(code int) *PluginsNetboxDNSRecordsDeleteDefault {
	return &PluginsNetboxDNSRecordsDeleteDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSRecordsDeleteDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSRecordsDeleteDefault plugins netbox dns records delete default
*/
type PluginsNetboxDNSRecordsDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns records delete default response has a 2xx status code
func (o *PluginsNetboxDNSRecordsDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns records delete default response has a 3xx status code
func (o *PluginsNetboxDNSRecordsDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns records delete default response has a 4xx status code
func (o *PluginsNetboxDNSRecordsDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns records delete default response has a 5xx status code
func (o *PluginsNetboxDNSRecordsDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns records delete default response a status code equal to that given
func (o *PluginsNetboxDNSRecordsDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns records delete default response
func (o *PluginsNetboxDNSRecordsDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSRecordsDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/records/{id}/][%d] plugins_netbox-dns_records_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/records/{id}/][%d] plugins_netbox-dns_records_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
