// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSZonesBulkPartialUpdateReader is a Reader for the PluginsNetboxDNSZonesBulkPartialUpdate structure.
type PluginsNetboxDNSZonesBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSZonesBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSZonesBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSZonesBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSZonesBulkPartialUpdateOK creates a PluginsNetboxDNSZonesBulkPartialUpdateOK with default headers values
func NewPluginsNetboxDNSZonesBulkPartialUpdateOK() *PluginsNetboxDNSZonesBulkPartialUpdateOK {
	return &PluginsNetboxDNSZonesBulkPartialUpdateOK{}
}

/*
PluginsNetboxDNSZonesBulkPartialUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSZonesBulkPartialUpdateOK plugins netbox Dns zones bulk partial update o k
*/
type PluginsNetboxDNSZonesBulkPartialUpdateOK struct {
	Payload *models.Zone
}

// IsSuccess returns true when this plugins netbox Dns zones bulk partial update o k response has a 2xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns zones bulk partial update o k response has a 3xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns zones bulk partial update o k response has a 4xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns zones bulk partial update o k response has a 5xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns zones bulk partial update o k response a status code equal to that given
func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns zones bulk partial update o k response
func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/zones/][%d] pluginsNetboxDnsZonesBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/zones/][%d] pluginsNetboxDnsZonesBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) GetPayload() *models.Zone {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSZonesBulkPartialUpdateDefault creates a PluginsNetboxDNSZonesBulkPartialUpdateDefault with default headers values
func NewPluginsNetboxDNSZonesBulkPartialUpdateDefault(code int) *PluginsNetboxDNSZonesBulkPartialUpdateDefault {
	return &PluginsNetboxDNSZonesBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSZonesBulkPartialUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSZonesBulkPartialUpdateDefault plugins netbox dns zones bulk partial update default
*/
type PluginsNetboxDNSZonesBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns zones bulk partial update default response has a 2xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns zones bulk partial update default response has a 3xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns zones bulk partial update default response has a 4xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns zones bulk partial update default response has a 5xx status code
func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns zones bulk partial update default response a status code equal to that given
func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns zones bulk partial update default response
func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/zones/][%d] plugins_netbox-dns_zones_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/zones/][%d] plugins_netbox-dns_zones_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
