// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSViewsUpdateReader is a Reader for the PluginsNetboxDNSViewsUpdate structure.
type PluginsNetboxDNSViewsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSViewsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSViewsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSViewsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSViewsUpdateOK creates a PluginsNetboxDNSViewsUpdateOK with default headers values
func NewPluginsNetboxDNSViewsUpdateOK() *PluginsNetboxDNSViewsUpdateOK {
	return &PluginsNetboxDNSViewsUpdateOK{}
}

/*
PluginsNetboxDNSViewsUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSViewsUpdateOK plugins netbox Dns views update o k
*/
type PluginsNetboxDNSViewsUpdateOK struct {
	Payload *models.View
}

// IsSuccess returns true when this plugins netbox Dns views update o k response has a 2xx status code
func (o *PluginsNetboxDNSViewsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns views update o k response has a 3xx status code
func (o *PluginsNetboxDNSViewsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns views update o k response has a 4xx status code
func (o *PluginsNetboxDNSViewsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns views update o k response has a 5xx status code
func (o *PluginsNetboxDNSViewsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns views update o k response a status code equal to that given
func (o *PluginsNetboxDNSViewsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns views update o k response
func (o *PluginsNetboxDNSViewsUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSViewsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/views/{id}/][%d] pluginsNetboxDnsViewsUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSViewsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/views/{id}/][%d] pluginsNetboxDnsViewsUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSViewsUpdateOK) GetPayload() *models.View {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.View)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSViewsUpdateDefault creates a PluginsNetboxDNSViewsUpdateDefault with default headers values
func NewPluginsNetboxDNSViewsUpdateDefault(code int) *PluginsNetboxDNSViewsUpdateDefault {
	return &PluginsNetboxDNSViewsUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSViewsUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSViewsUpdateDefault plugins netbox dns views update default
*/
type PluginsNetboxDNSViewsUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns views update default response has a 2xx status code
func (o *PluginsNetboxDNSViewsUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns views update default response has a 3xx status code
func (o *PluginsNetboxDNSViewsUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns views update default response has a 4xx status code
func (o *PluginsNetboxDNSViewsUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns views update default response has a 5xx status code
func (o *PluginsNetboxDNSViewsUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns views update default response a status code equal to that given
func (o *PluginsNetboxDNSViewsUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns views update default response
func (o *PluginsNetboxDNSViewsUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSViewsUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/views/{id}/][%d] plugins_netbox-dns_views_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/views/{id}/][%d] plugins_netbox-dns_views_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
