// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// NewPluginsNetboxDNSZonesPartialUpdateParams creates a new PluginsNetboxDNSZonesPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSZonesPartialUpdateParams() *PluginsNetboxDNSZonesPartialUpdateParams {
	return &PluginsNetboxDNSZonesPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSZonesPartialUpdateParamsWithTimeout creates a new PluginsNetboxDNSZonesPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSZonesPartialUpdateParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesPartialUpdateParams {
	return &PluginsNetboxDNSZonesPartialUpdateParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSZonesPartialUpdateParamsWithContext creates a new PluginsNetboxDNSZonesPartialUpdateParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSZonesPartialUpdateParamsWithContext(ctx context.Context) *PluginsNetboxDNSZonesPartialUpdateParams {
	return &PluginsNetboxDNSZonesPartialUpdateParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSZonesPartialUpdateParamsWithHTTPClient creates a new PluginsNetboxDNSZonesPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSZonesPartialUpdateParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesPartialUpdateParams {
	return &PluginsNetboxDNSZonesPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSZonesPartialUpdateParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns zones partial update operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSZonesPartialUpdateParams struct {

	// Data.
	Data *models.WritableZone

	/* ID.

	   A unique integer value identifying this zone.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns zones partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WithDefaults() *PluginsNetboxDNSZonesPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns zones partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WithContext(ctx context.Context) *PluginsNetboxDNSZonesPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WithData(data *models.WritableZone) *PluginsNetboxDNSZonesPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) SetData(data *models.WritableZone) {
	o.Data = data
}

// WithID adds the id to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WithID(id int64) *PluginsNetboxDNSZonesPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the plugins netbox dns zones partial update params
func (o *PluginsNetboxDNSZonesPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSZonesPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
