// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSZonesReadReader is a Reader for the PluginsNetboxDNSZonesRead structure.
type PluginsNetboxDNSZonesReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSZonesReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSZonesReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSZonesReadDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSZonesReadOK creates a PluginsNetboxDNSZonesReadOK with default headers values
func NewPluginsNetboxDNSZonesReadOK() *PluginsNetboxDNSZonesReadOK {
	return &PluginsNetboxDNSZonesReadOK{}
}

/*
PluginsNetboxDNSZonesReadOK describes a response with status code 200, with default header values.

PluginsNetboxDNSZonesReadOK plugins netbox Dns zones read o k
*/
type PluginsNetboxDNSZonesReadOK struct {
	Payload *models.Zone
}

// IsSuccess returns true when this plugins netbox Dns zones read o k response has a 2xx status code
func (o *PluginsNetboxDNSZonesReadOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns zones read o k response has a 3xx status code
func (o *PluginsNetboxDNSZonesReadOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns zones read o k response has a 4xx status code
func (o *PluginsNetboxDNSZonesReadOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns zones read o k response has a 5xx status code
func (o *PluginsNetboxDNSZonesReadOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns zones read o k response a status code equal to that given
func (o *PluginsNetboxDNSZonesReadOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns zones read o k response
func (o *PluginsNetboxDNSZonesReadOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSZonesReadOK) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/][%d] pluginsNetboxDnsZonesReadOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSZonesReadOK) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/][%d] pluginsNetboxDnsZonesReadOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSZonesReadOK) GetPayload() *models.Zone {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Zone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSZonesReadDefault creates a PluginsNetboxDNSZonesReadDefault with default headers values
func NewPluginsNetboxDNSZonesReadDefault(code int) *PluginsNetboxDNSZonesReadDefault {
	return &PluginsNetboxDNSZonesReadDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSZonesReadDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSZonesReadDefault plugins netbox dns zones read default
*/
type PluginsNetboxDNSZonesReadDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns zones read default response has a 2xx status code
func (o *PluginsNetboxDNSZonesReadDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns zones read default response has a 3xx status code
func (o *PluginsNetboxDNSZonesReadDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns zones read default response has a 4xx status code
func (o *PluginsNetboxDNSZonesReadDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns zones read default response has a 5xx status code
func (o *PluginsNetboxDNSZonesReadDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns zones read default response a status code equal to that given
func (o *PluginsNetboxDNSZonesReadDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns zones read default response
func (o *PluginsNetboxDNSZonesReadDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSZonesReadDefault) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/][%d] plugins_netbox-dns_zones_read default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesReadDefault) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/zones/{id}/][%d] plugins_netbox-dns_zones_read default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesReadDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesReadDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
