// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PluginsNetboxDNSZonesDeleteReader is a Reader for the PluginsNetboxDNSZonesDelete structure.
type PluginsNetboxDNSZonesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSZonesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPluginsNetboxDNSZonesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSZonesDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSZonesDeleteNoContent creates a PluginsNetboxDNSZonesDeleteNoContent with default headers values
func NewPluginsNetboxDNSZonesDeleteNoContent() *PluginsNetboxDNSZonesDeleteNoContent {
	return &PluginsNetboxDNSZonesDeleteNoContent{}
}

/*
PluginsNetboxDNSZonesDeleteNoContent describes a response with status code 204, with default header values.

PluginsNetboxDNSZonesDeleteNoContent plugins netbox Dns zones delete no content
*/
type PluginsNetboxDNSZonesDeleteNoContent struct {
}

// IsSuccess returns true when this plugins netbox Dns zones delete no content response has a 2xx status code
func (o *PluginsNetboxDNSZonesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns zones delete no content response has a 3xx status code
func (o *PluginsNetboxDNSZonesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns zones delete no content response has a 4xx status code
func (o *PluginsNetboxDNSZonesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns zones delete no content response has a 5xx status code
func (o *PluginsNetboxDNSZonesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns zones delete no content response a status code equal to that given
func (o *PluginsNetboxDNSZonesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the plugins netbox Dns zones delete no content response
func (o *PluginsNetboxDNSZonesDeleteNoContent) Code() int {
	return 204
}

func (o *PluginsNetboxDNSZonesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/zones/{id}/][%d] pluginsNetboxDnsZonesDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSZonesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/zones/{id}/][%d] pluginsNetboxDnsZonesDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSZonesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPluginsNetboxDNSZonesDeleteDefault creates a PluginsNetboxDNSZonesDeleteDefault with default headers values
func NewPluginsNetboxDNSZonesDeleteDefault(code int) *PluginsNetboxDNSZonesDeleteDefault {
	return &PluginsNetboxDNSZonesDeleteDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSZonesDeleteDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSZonesDeleteDefault plugins netbox dns zones delete default
*/
type PluginsNetboxDNSZonesDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns zones delete default response has a 2xx status code
func (o *PluginsNetboxDNSZonesDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns zones delete default response has a 3xx status code
func (o *PluginsNetboxDNSZonesDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns zones delete default response has a 4xx status code
func (o *PluginsNetboxDNSZonesDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns zones delete default response has a 5xx status code
func (o *PluginsNetboxDNSZonesDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns zones delete default response a status code equal to that given
func (o *PluginsNetboxDNSZonesDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns zones delete default response
func (o *PluginsNetboxDNSZonesDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSZonesDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/zones/{id}/][%d] plugins_netbox-dns_zones_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/zones/{id}/][%d] plugins_netbox-dns_zones_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSZonesDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSZonesDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
