// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// NewPluginsNetboxDNSZonesBulkPartialUpdateParams creates a new PluginsNetboxDNSZonesBulkPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSZonesBulkPartialUpdateParams() *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	return &PluginsNetboxDNSZonesBulkPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSZonesBulkPartialUpdateParamsWithTimeout creates a new PluginsNetboxDNSZonesBulkPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSZonesBulkPartialUpdateParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	return &PluginsNetboxDNSZonesBulkPartialUpdateParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSZonesBulkPartialUpdateParamsWithContext creates a new PluginsNetboxDNSZonesBulkPartialUpdateParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSZonesBulkPartialUpdateParamsWithContext(ctx context.Context) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	return &PluginsNetboxDNSZonesBulkPartialUpdateParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSZonesBulkPartialUpdateParamsWithHTTPClient creates a new PluginsNetboxDNSZonesBulkPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSZonesBulkPartialUpdateParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	return &PluginsNetboxDNSZonesBulkPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSZonesBulkPartialUpdateParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns zones bulk partial update operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSZonesBulkPartialUpdateParams struct {

	// Data.
	Data *models.WritableZone

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns zones bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) WithDefaults() *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns zones bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) WithContext(ctx context.Context) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) WithData(data *models.WritableZone) *PluginsNetboxDNSZonesBulkPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the plugins netbox dns zones bulk partial update params
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) SetData(data *models.WritableZone) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSZonesBulkPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
