// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// NewPluginsNetboxDNSNameserversUpdateParams creates a new PluginsNetboxDNSNameserversUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSNameserversUpdateParams() *PluginsNetboxDNSNameserversUpdateParams {
	return &PluginsNetboxDNSNameserversUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSNameserversUpdateParamsWithTimeout creates a new PluginsNetboxDNSNameserversUpdateParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSNameserversUpdateParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSNameserversUpdateParams {
	return &PluginsNetboxDNSNameserversUpdateParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSNameserversUpdateParamsWithContext creates a new PluginsNetboxDNSNameserversUpdateParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSNameserversUpdateParamsWithContext(ctx context.Context) *PluginsNetboxDNSNameserversUpdateParams {
	return &PluginsNetboxDNSNameserversUpdateParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSNameserversUpdateParamsWithHTTPClient creates a new PluginsNetboxDNSNameserversUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSNameserversUpdateParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSNameserversUpdateParams {
	return &PluginsNetboxDNSNameserversUpdateParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSNameserversUpdateParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns nameservers update operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSNameserversUpdateParams struct {

	// Data.
	Data *models.NameServer

	/* ID.

	   A unique integer value identifying this name server.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns nameservers update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSNameserversUpdateParams) WithDefaults() *PluginsNetboxDNSNameserversUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns nameservers update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSNameserversUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSNameserversUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) WithContext(ctx context.Context) *PluginsNetboxDNSNameserversUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSNameserversUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) WithData(data *models.NameServer) *PluginsNetboxDNSNameserversUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) SetData(data *models.NameServer) {
	o.Data = data
}

// WithID adds the id to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) WithID(id int64) *PluginsNetboxDNSNameserversUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the plugins netbox dns nameservers update params
func (o *PluginsNetboxDNSNameserversUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSNameserversUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
