// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSRecordsPartialUpdateReader is a Reader for the PluginsNetboxDNSRecordsPartialUpdate structure.
type PluginsNetboxDNSRecordsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSRecordsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSRecordsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSRecordsPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSRecordsPartialUpdateOK creates a PluginsNetboxDNSRecordsPartialUpdateOK with default headers values
func NewPluginsNetboxDNSRecordsPartialUpdateOK() *PluginsNetboxDNSRecordsPartialUpdateOK {
	return &PluginsNetboxDNSRecordsPartialUpdateOK{}
}

/*
PluginsNetboxDNSRecordsPartialUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSRecordsPartialUpdateOK plugins netbox Dns records partial update o k
*/
type PluginsNetboxDNSRecordsPartialUpdateOK struct {
	Payload *models.Record
}

// IsSuccess returns true when this plugins netbox Dns records partial update o k response has a 2xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns records partial update o k response has a 3xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns records partial update o k response has a 4xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns records partial update o k response has a 5xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns records partial update o k response a status code equal to that given
func (o *PluginsNetboxDNSRecordsPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns records partial update o k response
func (o *PluginsNetboxDNSRecordsPartialUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSRecordsPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/records/{id}/][%d] pluginsNetboxDnsRecordsPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSRecordsPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/records/{id}/][%d] pluginsNetboxDnsRecordsPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSRecordsPartialUpdateOK) GetPayload() *models.Record {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Record)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSRecordsPartialUpdateDefault creates a PluginsNetboxDNSRecordsPartialUpdateDefault with default headers values
func NewPluginsNetboxDNSRecordsPartialUpdateDefault(code int) *PluginsNetboxDNSRecordsPartialUpdateDefault {
	return &PluginsNetboxDNSRecordsPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSRecordsPartialUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSRecordsPartialUpdateDefault plugins netbox dns records partial update default
*/
type PluginsNetboxDNSRecordsPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns records partial update default response has a 2xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns records partial update default response has a 3xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns records partial update default response has a 4xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns records partial update default response has a 5xx status code
func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns records partial update default response a status code equal to that given
func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns records partial update default response
func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/records/{id}/][%d] plugins_netbox-dns_records_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/records/{id}/][%d] plugins_netbox-dns_records_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
