// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSRecordsUpdateReader is a Reader for the PluginsNetboxDNSRecordsUpdate structure.
type PluginsNetboxDNSRecordsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSRecordsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSRecordsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSRecordsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSRecordsUpdateOK creates a PluginsNetboxDNSRecordsUpdateOK with default headers values
func NewPluginsNetboxDNSRecordsUpdateOK() *PluginsNetboxDNSRecordsUpdateOK {
	return &PluginsNetboxDNSRecordsUpdateOK{}
}

/*
PluginsNetboxDNSRecordsUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSRecordsUpdateOK plugins netbox Dns records update o k
*/
type PluginsNetboxDNSRecordsUpdateOK struct {
	Payload *models.Record
}

// IsSuccess returns true when this plugins netbox Dns records update o k response has a 2xx status code
func (o *PluginsNetboxDNSRecordsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns records update o k response has a 3xx status code
func (o *PluginsNetboxDNSRecordsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns records update o k response has a 4xx status code
func (o *PluginsNetboxDNSRecordsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns records update o k response has a 5xx status code
func (o *PluginsNetboxDNSRecordsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns records update o k response a status code equal to that given
func (o *PluginsNetboxDNSRecordsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns records update o k response
func (o *PluginsNetboxDNSRecordsUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSRecordsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/records/{id}/][%d] pluginsNetboxDnsRecordsUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSRecordsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/records/{id}/][%d] pluginsNetboxDnsRecordsUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSRecordsUpdateOK) GetPayload() *models.Record {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Record)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSRecordsUpdateDefault creates a PluginsNetboxDNSRecordsUpdateDefault with default headers values
func NewPluginsNetboxDNSRecordsUpdateDefault(code int) *PluginsNetboxDNSRecordsUpdateDefault {
	return &PluginsNetboxDNSRecordsUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSRecordsUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSRecordsUpdateDefault plugins netbox dns records update default
*/
type PluginsNetboxDNSRecordsUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns records update default response has a 2xx status code
func (o *PluginsNetboxDNSRecordsUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns records update default response has a 3xx status code
func (o *PluginsNetboxDNSRecordsUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns records update default response has a 4xx status code
func (o *PluginsNetboxDNSRecordsUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns records update default response has a 5xx status code
func (o *PluginsNetboxDNSRecordsUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns records update default response a status code equal to that given
func (o *PluginsNetboxDNSRecordsUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns records update default response
func (o *PluginsNetboxDNSRecordsUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSRecordsUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/records/{id}/][%d] plugins_netbox-dns_records_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/records/{id}/][%d] plugins_netbox-dns_records_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
