// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSNameserversBulkUpdateReader is a Reader for the PluginsNetboxDNSNameserversBulkUpdate structure.
type PluginsNetboxDNSNameserversBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSNameserversBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSNameserversBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSNameserversBulkUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSNameserversBulkUpdateOK creates a PluginsNetboxDNSNameserversBulkUpdateOK with default headers values
func NewPluginsNetboxDNSNameserversBulkUpdateOK() *PluginsNetboxDNSNameserversBulkUpdateOK {
	return &PluginsNetboxDNSNameserversBulkUpdateOK{}
}

/*
PluginsNetboxDNSNameserversBulkUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSNameserversBulkUpdateOK plugins netbox Dns nameservers bulk update o k
*/
type PluginsNetboxDNSNameserversBulkUpdateOK struct {
	Payload *models.NameServer
}

// IsSuccess returns true when this plugins netbox Dns nameservers bulk update o k response has a 2xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns nameservers bulk update o k response has a 3xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns nameservers bulk update o k response has a 4xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns nameservers bulk update o k response has a 5xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns nameservers bulk update o k response a status code equal to that given
func (o *PluginsNetboxDNSNameserversBulkUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns nameservers bulk update o k response
func (o *PluginsNetboxDNSNameserversBulkUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSNameserversBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/nameservers/][%d] pluginsNetboxDnsNameserversBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkUpdateOK) String() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/nameservers/][%d] pluginsNetboxDnsNameserversBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkUpdateOK) GetPayload() *models.NameServer {
	return o.Payload
}

func (o *PluginsNetboxDNSNameserversBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NameServer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSNameserversBulkUpdateDefault creates a PluginsNetboxDNSNameserversBulkUpdateDefault with default headers values
func NewPluginsNetboxDNSNameserversBulkUpdateDefault(code int) *PluginsNetboxDNSNameserversBulkUpdateDefault {
	return &PluginsNetboxDNSNameserversBulkUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSNameserversBulkUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSNameserversBulkUpdateDefault plugins netbox dns nameservers bulk update default
*/
type PluginsNetboxDNSNameserversBulkUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns nameservers bulk update default response has a 2xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns nameservers bulk update default response has a 3xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns nameservers bulk update default response has a 4xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns nameservers bulk update default response has a 5xx status code
func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns nameservers bulk update default response a status code equal to that given
func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns nameservers bulk update default response
func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/nameservers/][%d] plugins_netbox-dns_nameservers_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) String() string {
	return fmt.Sprintf("[PUT /plugins/netbox-dns/nameservers/][%d] plugins_netbox-dns_nameservers_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSNameserversBulkUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
