// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// NewPluginsNetboxDNSRecordsBulkPartialUpdateParams creates a new PluginsNetboxDNSRecordsBulkPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSRecordsBulkPartialUpdateParams() *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	return &PluginsNetboxDNSRecordsBulkPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSRecordsBulkPartialUpdateParamsWithTimeout creates a new PluginsNetboxDNSRecordsBulkPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSRecordsBulkPartialUpdateParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	return &PluginsNetboxDNSRecordsBulkPartialUpdateParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSRecordsBulkPartialUpdateParamsWithContext creates a new PluginsNetboxDNSRecordsBulkPartialUpdateParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSRecordsBulkPartialUpdateParamsWithContext(ctx context.Context) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	return &PluginsNetboxDNSRecordsBulkPartialUpdateParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSRecordsBulkPartialUpdateParamsWithHTTPClient creates a new PluginsNetboxDNSRecordsBulkPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSRecordsBulkPartialUpdateParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	return &PluginsNetboxDNSRecordsBulkPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSRecordsBulkPartialUpdateParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns records bulk partial update operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSRecordsBulkPartialUpdateParams struct {

	// Data.
	Data *models.WritableRecord

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns records bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) WithDefaults() *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns records bulk partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) WithContext(ctx context.Context) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) WithData(data *models.WritableRecord) *PluginsNetboxDNSRecordsBulkPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the plugins netbox dns records bulk partial update params
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) SetData(data *models.WritableRecord) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSRecordsBulkPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
