// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSViewsCreateReader is a Reader for the PluginsNetboxDNSViewsCreate structure.
type PluginsNetboxDNSViewsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSViewsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPluginsNetboxDNSViewsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSViewsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSViewsCreateCreated creates a PluginsNetboxDNSViewsCreateCreated with default headers values
func NewPluginsNetboxDNSViewsCreateCreated() *PluginsNetboxDNSViewsCreateCreated {
	return &PluginsNetboxDNSViewsCreateCreated{}
}

/*
PluginsNetboxDNSViewsCreateCreated describes a response with status code 201, with default header values.

PluginsNetboxDNSViewsCreateCreated plugins netbox Dns views create created
*/
type PluginsNetboxDNSViewsCreateCreated struct {
	Payload *models.View
}

// IsSuccess returns true when this plugins netbox Dns views create created response has a 2xx status code
func (o *PluginsNetboxDNSViewsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns views create created response has a 3xx status code
func (o *PluginsNetboxDNSViewsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns views create created response has a 4xx status code
func (o *PluginsNetboxDNSViewsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns views create created response has a 5xx status code
func (o *PluginsNetboxDNSViewsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns views create created response a status code equal to that given
func (o *PluginsNetboxDNSViewsCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the plugins netbox Dns views create created response
func (o *PluginsNetboxDNSViewsCreateCreated) Code() int {
	return 201
}

func (o *PluginsNetboxDNSViewsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /plugins/netbox-dns/views/][%d] pluginsNetboxDnsViewsCreateCreated  %+v", 201, o.Payload)
}

func (o *PluginsNetboxDNSViewsCreateCreated) String() string {
	return fmt.Sprintf("[POST /plugins/netbox-dns/views/][%d] pluginsNetboxDnsViewsCreateCreated  %+v", 201, o.Payload)
}

func (o *PluginsNetboxDNSViewsCreateCreated) GetPayload() *models.View {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.View)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSViewsCreateDefault creates a PluginsNetboxDNSViewsCreateDefault with default headers values
func NewPluginsNetboxDNSViewsCreateDefault(code int) *PluginsNetboxDNSViewsCreateDefault {
	return &PluginsNetboxDNSViewsCreateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSViewsCreateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSViewsCreateDefault plugins netbox dns views create default
*/
type PluginsNetboxDNSViewsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns views create default response has a 2xx status code
func (o *PluginsNetboxDNSViewsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns views create default response has a 3xx status code
func (o *PluginsNetboxDNSViewsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns views create default response has a 4xx status code
func (o *PluginsNetboxDNSViewsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns views create default response has a 5xx status code
func (o *PluginsNetboxDNSViewsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns views create default response a status code equal to that given
func (o *PluginsNetboxDNSViewsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns views create default response
func (o *PluginsNetboxDNSViewsCreateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSViewsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /plugins/netbox-dns/views/][%d] plugins_netbox-dns_views_create default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsCreateDefault) String() string {
	return fmt.Sprintf("[POST /plugins/netbox-dns/views/][%d] plugins_netbox-dns_views_create default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
