// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PluginsNetboxDNSViewsBulkDeleteReader is a Reader for the PluginsNetboxDNSViewsBulkDelete structure.
type PluginsNetboxDNSViewsBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSViewsBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPluginsNetboxDNSViewsBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSViewsBulkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSViewsBulkDeleteNoContent creates a PluginsNetboxDNSViewsBulkDeleteNoContent with default headers values
func NewPluginsNetboxDNSViewsBulkDeleteNoContent() *PluginsNetboxDNSViewsBulkDeleteNoContent {
	return &PluginsNetboxDNSViewsBulkDeleteNoContent{}
}

/*
PluginsNetboxDNSViewsBulkDeleteNoContent describes a response with status code 204, with default header values.

PluginsNetboxDNSViewsBulkDeleteNoContent plugins netbox Dns views bulk delete no content
*/
type PluginsNetboxDNSViewsBulkDeleteNoContent struct {
}

// IsSuccess returns true when this plugins netbox Dns views bulk delete no content response has a 2xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns views bulk delete no content response has a 3xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns views bulk delete no content response has a 4xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns views bulk delete no content response has a 5xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns views bulk delete no content response a status code equal to that given
func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the plugins netbox Dns views bulk delete no content response
func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) Code() int {
	return 204
}

func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/views/][%d] pluginsNetboxDnsViewsBulkDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/views/][%d] pluginsNetboxDnsViewsBulkDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSViewsBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPluginsNetboxDNSViewsBulkDeleteDefault creates a PluginsNetboxDNSViewsBulkDeleteDefault with default headers values
func NewPluginsNetboxDNSViewsBulkDeleteDefault(code int) *PluginsNetboxDNSViewsBulkDeleteDefault {
	return &PluginsNetboxDNSViewsBulkDeleteDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSViewsBulkDeleteDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSViewsBulkDeleteDefault plugins netbox dns views bulk delete default
*/
type PluginsNetboxDNSViewsBulkDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns views bulk delete default response has a 2xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns views bulk delete default response has a 3xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns views bulk delete default response has a 4xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns views bulk delete default response has a 5xx status code
func (o *PluginsNetboxDNSViewsBulkDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns views bulk delete default response a status code equal to that given
func (o *PluginsNetboxDNSViewsBulkDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns views bulk delete default response
func (o *PluginsNetboxDNSViewsBulkDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSViewsBulkDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/views/][%d] plugins_netbox-dns_views_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsBulkDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/views/][%d] plugins_netbox-dns_views_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsBulkDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsBulkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
