// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PluginsNetboxDNSNameserversDeleteReader is a Reader for the PluginsNetboxDNSNameserversDelete structure.
type PluginsNetboxDNSNameserversDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSNameserversDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPluginsNetboxDNSNameserversDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSNameserversDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSNameserversDeleteNoContent creates a PluginsNetboxDNSNameserversDeleteNoContent with default headers values
func NewPluginsNetboxDNSNameserversDeleteNoContent() *PluginsNetboxDNSNameserversDeleteNoContent {
	return &PluginsNetboxDNSNameserversDeleteNoContent{}
}

/*
PluginsNetboxDNSNameserversDeleteNoContent describes a response with status code 204, with default header values.

PluginsNetboxDNSNameserversDeleteNoContent plugins netbox Dns nameservers delete no content
*/
type PluginsNetboxDNSNameserversDeleteNoContent struct {
}

// IsSuccess returns true when this plugins netbox Dns nameservers delete no content response has a 2xx status code
func (o *PluginsNetboxDNSNameserversDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns nameservers delete no content response has a 3xx status code
func (o *PluginsNetboxDNSNameserversDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns nameservers delete no content response has a 4xx status code
func (o *PluginsNetboxDNSNameserversDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns nameservers delete no content response has a 5xx status code
func (o *PluginsNetboxDNSNameserversDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns nameservers delete no content response a status code equal to that given
func (o *PluginsNetboxDNSNameserversDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the plugins netbox Dns nameservers delete no content response
func (o *PluginsNetboxDNSNameserversDeleteNoContent) Code() int {
	return 204
}

func (o *PluginsNetboxDNSNameserversDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/{id}/][%d] pluginsNetboxDnsNameserversDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSNameserversDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/{id}/][%d] pluginsNetboxDnsNameserversDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSNameserversDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPluginsNetboxDNSNameserversDeleteDefault creates a PluginsNetboxDNSNameserversDeleteDefault with default headers values
func NewPluginsNetboxDNSNameserversDeleteDefault(code int) *PluginsNetboxDNSNameserversDeleteDefault {
	return &PluginsNetboxDNSNameserversDeleteDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSNameserversDeleteDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSNameserversDeleteDefault plugins netbox dns nameservers delete default
*/
type PluginsNetboxDNSNameserversDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns nameservers delete default response has a 2xx status code
func (o *PluginsNetboxDNSNameserversDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns nameservers delete default response has a 3xx status code
func (o *PluginsNetboxDNSNameserversDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns nameservers delete default response has a 4xx status code
func (o *PluginsNetboxDNSNameserversDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns nameservers delete default response has a 5xx status code
func (o *PluginsNetboxDNSNameserversDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns nameservers delete default response a status code equal to that given
func (o *PluginsNetboxDNSNameserversDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns nameservers delete default response
func (o *PluginsNetboxDNSNameserversDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSNameserversDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/{id}/][%d] plugins_netbox-dns_nameservers_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/{id}/][%d] plugins_netbox-dns_nameservers_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSNameserversDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
