// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PluginsNetboxDNSNameserversBulkDeleteReader is a Reader for the PluginsNetboxDNSNameserversBulkDelete structure.
type PluginsNetboxDNSNameserversBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSNameserversBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPluginsNetboxDNSNameserversBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSNameserversBulkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSNameserversBulkDeleteNoContent creates a PluginsNetboxDNSNameserversBulkDeleteNoContent with default headers values
func NewPluginsNetboxDNSNameserversBulkDeleteNoContent() *PluginsNetboxDNSNameserversBulkDeleteNoContent {
	return &PluginsNetboxDNSNameserversBulkDeleteNoContent{}
}

/*
PluginsNetboxDNSNameserversBulkDeleteNoContent describes a response with status code 204, with default header values.

PluginsNetboxDNSNameserversBulkDeleteNoContent plugins netbox Dns nameservers bulk delete no content
*/
type PluginsNetboxDNSNameserversBulkDeleteNoContent struct {
}

// IsSuccess returns true when this plugins netbox Dns nameservers bulk delete no content response has a 2xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns nameservers bulk delete no content response has a 3xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns nameservers bulk delete no content response has a 4xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns nameservers bulk delete no content response has a 5xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns nameservers bulk delete no content response a status code equal to that given
func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the plugins netbox Dns nameservers bulk delete no content response
func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) Code() int {
	return 204
}

func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/][%d] pluginsNetboxDnsNameserversBulkDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/][%d] pluginsNetboxDnsNameserversBulkDeleteNoContent ", 204)
}

func (o *PluginsNetboxDNSNameserversBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPluginsNetboxDNSNameserversBulkDeleteDefault creates a PluginsNetboxDNSNameserversBulkDeleteDefault with default headers values
func NewPluginsNetboxDNSNameserversBulkDeleteDefault(code int) *PluginsNetboxDNSNameserversBulkDeleteDefault {
	return &PluginsNetboxDNSNameserversBulkDeleteDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSNameserversBulkDeleteDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSNameserversBulkDeleteDefault plugins netbox dns nameservers bulk delete default
*/
type PluginsNetboxDNSNameserversBulkDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns nameservers bulk delete default response has a 2xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns nameservers bulk delete default response has a 3xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns nameservers bulk delete default response has a 4xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns nameservers bulk delete default response has a 5xx status code
func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns nameservers bulk delete default response a status code equal to that given
func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns nameservers bulk delete default response
func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/][%d] plugins_netbox-dns_nameservers_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) String() string {
	return fmt.Sprintf("[DELETE /plugins/netbox-dns/nameservers/][%d] plugins_netbox-dns_nameservers_bulk_delete default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSNameserversBulkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
