// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPluginsNetboxDNSNameserversBulkDeleteParams creates a new PluginsNetboxDNSNameserversBulkDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSNameserversBulkDeleteParams() *PluginsNetboxDNSNameserversBulkDeleteParams {
	return &PluginsNetboxDNSNameserversBulkDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSNameserversBulkDeleteParamsWithTimeout creates a new PluginsNetboxDNSNameserversBulkDeleteParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSNameserversBulkDeleteParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSNameserversBulkDeleteParams {
	return &PluginsNetboxDNSNameserversBulkDeleteParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSNameserversBulkDeleteParamsWithContext creates a new PluginsNetboxDNSNameserversBulkDeleteParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSNameserversBulkDeleteParamsWithContext(ctx context.Context) *PluginsNetboxDNSNameserversBulkDeleteParams {
	return &PluginsNetboxDNSNameserversBulkDeleteParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSNameserversBulkDeleteParamsWithHTTPClient creates a new PluginsNetboxDNSNameserversBulkDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSNameserversBulkDeleteParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSNameserversBulkDeleteParams {
	return &PluginsNetboxDNSNameserversBulkDeleteParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSNameserversBulkDeleteParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns nameservers bulk delete operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSNameserversBulkDeleteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns nameservers bulk delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) WithDefaults() *PluginsNetboxDNSNameserversBulkDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns nameservers bulk delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns nameservers bulk delete params
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSNameserversBulkDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns nameservers bulk delete params
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns nameservers bulk delete params
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) WithContext(ctx context.Context) *PluginsNetboxDNSNameserversBulkDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns nameservers bulk delete params
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns nameservers bulk delete params
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSNameserversBulkDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns nameservers bulk delete params
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSNameserversBulkDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
