// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPluginsNetboxDNSZonesBulkDeleteParams creates a new PluginsNetboxDNSZonesBulkDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSZonesBulkDeleteParams() *PluginsNetboxDNSZonesBulkDeleteParams {
	return &PluginsNetboxDNSZonesBulkDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSZonesBulkDeleteParamsWithTimeout creates a new PluginsNetboxDNSZonesBulkDeleteParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSZonesBulkDeleteParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesBulkDeleteParams {
	return &PluginsNetboxDNSZonesBulkDeleteParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSZonesBulkDeleteParamsWithContext creates a new PluginsNetboxDNSZonesBulkDeleteParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSZonesBulkDeleteParamsWithContext(ctx context.Context) *PluginsNetboxDNSZonesBulkDeleteParams {
	return &PluginsNetboxDNSZonesBulkDeleteParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSZonesBulkDeleteParamsWithHTTPClient creates a new PluginsNetboxDNSZonesBulkDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSZonesBulkDeleteParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesBulkDeleteParams {
	return &PluginsNetboxDNSZonesBulkDeleteParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSZonesBulkDeleteParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns zones bulk delete operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSZonesBulkDeleteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns zones bulk delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesBulkDeleteParams) WithDefaults() *PluginsNetboxDNSZonesBulkDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns zones bulk delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesBulkDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns zones bulk delete params
func (o *PluginsNetboxDNSZonesBulkDeleteParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesBulkDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns zones bulk delete params
func (o *PluginsNetboxDNSZonesBulkDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns zones bulk delete params
func (o *PluginsNetboxDNSZonesBulkDeleteParams) WithContext(ctx context.Context) *PluginsNetboxDNSZonesBulkDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns zones bulk delete params
func (o *PluginsNetboxDNSZonesBulkDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns zones bulk delete params
func (o *PluginsNetboxDNSZonesBulkDeleteParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesBulkDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns zones bulk delete params
func (o *PluginsNetboxDNSZonesBulkDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSZonesBulkDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
