// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPluginsNetboxDNSZonesReadParams creates a new PluginsNetboxDNSZonesReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSZonesReadParams() *PluginsNetboxDNSZonesReadParams {
	return &PluginsNetboxDNSZonesReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSZonesReadParamsWithTimeout creates a new PluginsNetboxDNSZonesReadParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSZonesReadParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesReadParams {
	return &PluginsNetboxDNSZonesReadParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSZonesReadParamsWithContext creates a new PluginsNetboxDNSZonesReadParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSZonesReadParamsWithContext(ctx context.Context) *PluginsNetboxDNSZonesReadParams {
	return &PluginsNetboxDNSZonesReadParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSZonesReadParamsWithHTTPClient creates a new PluginsNetboxDNSZonesReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSZonesReadParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesReadParams {
	return &PluginsNetboxDNSZonesReadParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSZonesReadParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns zones read operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSZonesReadParams struct {

	/* ID.

	   A unique integer value identifying this zone.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns zones read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesReadParams) WithDefaults() *PluginsNetboxDNSZonesReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns zones read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) WithContext(ctx context.Context) *PluginsNetboxDNSZonesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) WithID(id int64) *PluginsNetboxDNSZonesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the plugins netbox dns zones read params
func (o *PluginsNetboxDNSZonesReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSZonesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
