// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSViewsViewsReader is a Reader for the PluginsNetboxDNSViewsViews structure.
type PluginsNetboxDNSViewsViewsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSViewsViewsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSViewsViewsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSViewsViewsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSViewsViewsOK creates a PluginsNetboxDNSViewsViewsOK with default headers values
func NewPluginsNetboxDNSViewsViewsOK() *PluginsNetboxDNSViewsViewsOK {
	return &PluginsNetboxDNSViewsViewsOK{}
}

/*
PluginsNetboxDNSViewsViewsOK describes a response with status code 200, with default header values.

PluginsNetboxDNSViewsViewsOK plugins netbox Dns views views o k
*/
type PluginsNetboxDNSViewsViewsOK struct {
	Payload *models.View
}

// IsSuccess returns true when this plugins netbox Dns views views o k response has a 2xx status code
func (o *PluginsNetboxDNSViewsViewsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns views views o k response has a 3xx status code
func (o *PluginsNetboxDNSViewsViewsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns views views o k response has a 4xx status code
func (o *PluginsNetboxDNSViewsViewsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns views views o k response has a 5xx status code
func (o *PluginsNetboxDNSViewsViewsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns views views o k response a status code equal to that given
func (o *PluginsNetboxDNSViewsViewsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns views views o k response
func (o *PluginsNetboxDNSViewsViewsOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSViewsViewsOK) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/views/{id}/views/][%d] pluginsNetboxDnsViewsViewsOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSViewsViewsOK) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/views/{id}/views/][%d] pluginsNetboxDnsViewsViewsOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSViewsViewsOK) GetPayload() *models.View {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsViewsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.View)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSViewsViewsDefault creates a PluginsNetboxDNSViewsViewsDefault with default headers values
func NewPluginsNetboxDNSViewsViewsDefault(code int) *PluginsNetboxDNSViewsViewsDefault {
	return &PluginsNetboxDNSViewsViewsDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSViewsViewsDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSViewsViewsDefault plugins netbox dns views views default
*/
type PluginsNetboxDNSViewsViewsDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns views views default response has a 2xx status code
func (o *PluginsNetboxDNSViewsViewsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns views views default response has a 3xx status code
func (o *PluginsNetboxDNSViewsViewsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns views views default response has a 4xx status code
func (o *PluginsNetboxDNSViewsViewsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns views views default response has a 5xx status code
func (o *PluginsNetboxDNSViewsViewsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns views views default response a status code equal to that given
func (o *PluginsNetboxDNSViewsViewsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns views views default response
func (o *PluginsNetboxDNSViewsViewsDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSViewsViewsDefault) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/views/{id}/views/][%d] plugins_netbox-dns_views_views default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsViewsDefault) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/views/{id}/views/][%d] plugins_netbox-dns_views_views default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsViewsDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsViewsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
