// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// NewPluginsNetboxDNSZonesCreateParams creates a new PluginsNetboxDNSZonesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSZonesCreateParams() *PluginsNetboxDNSZonesCreateParams {
	return &PluginsNetboxDNSZonesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSZonesCreateParamsWithTimeout creates a new PluginsNetboxDNSZonesCreateParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSZonesCreateParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesCreateParams {
	return &PluginsNetboxDNSZonesCreateParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSZonesCreateParamsWithContext creates a new PluginsNetboxDNSZonesCreateParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSZonesCreateParamsWithContext(ctx context.Context) *PluginsNetboxDNSZonesCreateParams {
	return &PluginsNetboxDNSZonesCreateParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSZonesCreateParamsWithHTTPClient creates a new PluginsNetboxDNSZonesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSZonesCreateParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesCreateParams {
	return &PluginsNetboxDNSZonesCreateParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSZonesCreateParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns zones create operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSZonesCreateParams struct {

	// Data.
	Data *models.WritableZone

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns zones create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesCreateParams) WithDefaults() *PluginsNetboxDNSZonesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns zones create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSZonesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSZonesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) WithContext(ctx context.Context) *PluginsNetboxDNSZonesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSZonesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) WithData(data *models.WritableZone) *PluginsNetboxDNSZonesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the plugins netbox dns zones create params
func (o *PluginsNetboxDNSZonesCreateParams) SetData(data *models.WritableZone) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSZonesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
