// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSViewsBulkPartialUpdateReader is a Reader for the PluginsNetboxDNSViewsBulkPartialUpdate structure.
type PluginsNetboxDNSViewsBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSViewsBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSViewsBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSViewsBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSViewsBulkPartialUpdateOK creates a PluginsNetboxDNSViewsBulkPartialUpdateOK with default headers values
func NewPluginsNetboxDNSViewsBulkPartialUpdateOK() *PluginsNetboxDNSViewsBulkPartialUpdateOK {
	return &PluginsNetboxDNSViewsBulkPartialUpdateOK{}
}

/*
PluginsNetboxDNSViewsBulkPartialUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSViewsBulkPartialUpdateOK plugins netbox Dns views bulk partial update o k
*/
type PluginsNetboxDNSViewsBulkPartialUpdateOK struct {
	Payload *models.View
}

// IsSuccess returns true when this plugins netbox Dns views bulk partial update o k response has a 2xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns views bulk partial update o k response has a 3xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns views bulk partial update o k response has a 4xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns views bulk partial update o k response has a 5xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns views bulk partial update o k response a status code equal to that given
func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns views bulk partial update o k response
func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/views/][%d] pluginsNetboxDnsViewsBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/views/][%d] pluginsNetboxDnsViewsBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) GetPayload() *models.View {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.View)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSViewsBulkPartialUpdateDefault creates a PluginsNetboxDNSViewsBulkPartialUpdateDefault with default headers values
func NewPluginsNetboxDNSViewsBulkPartialUpdateDefault(code int) *PluginsNetboxDNSViewsBulkPartialUpdateDefault {
	return &PluginsNetboxDNSViewsBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSViewsBulkPartialUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSViewsBulkPartialUpdateDefault plugins netbox dns views bulk partial update default
*/
type PluginsNetboxDNSViewsBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns views bulk partial update default response has a 2xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns views bulk partial update default response has a 3xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns views bulk partial update default response has a 4xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns views bulk partial update default response has a 5xx status code
func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns views bulk partial update default response a status code equal to that given
func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns views bulk partial update default response
func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/views/][%d] plugins_netbox-dns_views_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/views/][%d] plugins_netbox-dns_views_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSViewsBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
