// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSRecordsListReader is a Reader for the PluginsNetboxDNSRecordsList structure.
type PluginsNetboxDNSRecordsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSRecordsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSRecordsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSRecordsListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSRecordsListOK creates a PluginsNetboxDNSRecordsListOK with default headers values
func NewPluginsNetboxDNSRecordsListOK() *PluginsNetboxDNSRecordsListOK {
	return &PluginsNetboxDNSRecordsListOK{}
}

/*
PluginsNetboxDNSRecordsListOK describes a response with status code 200, with default header values.

PluginsNetboxDNSRecordsListOK plugins netbox Dns records list o k
*/
type PluginsNetboxDNSRecordsListOK struct {
	Payload *PluginsNetboxDNSRecordsListOKBody
}

// IsSuccess returns true when this plugins netbox Dns records list o k response has a 2xx status code
func (o *PluginsNetboxDNSRecordsListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns records list o k response has a 3xx status code
func (o *PluginsNetboxDNSRecordsListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns records list o k response has a 4xx status code
func (o *PluginsNetboxDNSRecordsListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns records list o k response has a 5xx status code
func (o *PluginsNetboxDNSRecordsListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns records list o k response a status code equal to that given
func (o *PluginsNetboxDNSRecordsListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns records list o k response
func (o *PluginsNetboxDNSRecordsListOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSRecordsListOK) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/records/][%d] pluginsNetboxDnsRecordsListOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSRecordsListOK) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/records/][%d] pluginsNetboxDnsRecordsListOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSRecordsListOK) GetPayload() *PluginsNetboxDNSRecordsListOKBody {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PluginsNetboxDNSRecordsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSRecordsListDefault creates a PluginsNetboxDNSRecordsListDefault with default headers values
func NewPluginsNetboxDNSRecordsListDefault(code int) *PluginsNetboxDNSRecordsListDefault {
	return &PluginsNetboxDNSRecordsListDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSRecordsListDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSRecordsListDefault plugins netbox dns records list default
*/
type PluginsNetboxDNSRecordsListDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns records list default response has a 2xx status code
func (o *PluginsNetboxDNSRecordsListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns records list default response has a 3xx status code
func (o *PluginsNetboxDNSRecordsListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns records list default response has a 4xx status code
func (o *PluginsNetboxDNSRecordsListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns records list default response has a 5xx status code
func (o *PluginsNetboxDNSRecordsListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns records list default response a status code equal to that given
func (o *PluginsNetboxDNSRecordsListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns records list default response
func (o *PluginsNetboxDNSRecordsListDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSRecordsListDefault) Error() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/records/][%d] plugins_netbox-dns_records_list default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsListDefault) String() string {
	return fmt.Sprintf("[GET /plugins/netbox-dns/records/][%d] plugins_netbox-dns_records_list default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSRecordsListDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSRecordsListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PluginsNetboxDNSRecordsListOKBody plugins netbox DNS records list o k body
swagger:model PluginsNetboxDNSRecordsListOKBody
*/
type PluginsNetboxDNSRecordsListOKBody struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// next
	// Format: uri
	Next *strfmt.URI `json:"next,omitempty"`

	// previous
	// Format: uri
	Previous *strfmt.URI `json:"previous,omitempty"`

	// results
	// Required: true
	Results []*models.Record `json:"results"`
}

// Validate validates this plugins netbox DNS records list o k body
func (o *PluginsNetboxDNSRecordsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PluginsNetboxDNSRecordsListOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("pluginsNetboxDnsRecordsListOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

func (o *PluginsNetboxDNSRecordsListOKBody) validateNext(formats strfmt.Registry) error {
	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if err := validate.FormatOf("pluginsNetboxDnsRecordsListOK"+"."+"next", "body", "uri", o.Next.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *PluginsNetboxDNSRecordsListOKBody) validatePrevious(formats strfmt.Registry) error {
	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if err := validate.FormatOf("pluginsNetboxDnsRecordsListOK"+"."+"previous", "body", "uri", o.Previous.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *PluginsNetboxDNSRecordsListOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("pluginsNetboxDnsRecordsListOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pluginsNetboxDnsRecordsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("pluginsNetboxDnsRecordsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this plugins netbox DNS records list o k body based on the context it is used
func (o *PluginsNetboxDNSRecordsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PluginsNetboxDNSRecordsListOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {
			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pluginsNetboxDnsRecordsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("pluginsNetboxDnsRecordsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PluginsNetboxDNSRecordsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PluginsNetboxDNSRecordsListOKBody) UnmarshalBinary(b []byte) error {
	var res PluginsNetboxDNSRecordsListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
