// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ProtonMail/go-netbox-dns/netbox_dns/models"
)

// PluginsNetboxDNSNameserversBulkPartialUpdateReader is a Reader for the PluginsNetboxDNSNameserversBulkPartialUpdate structure.
type PluginsNetboxDNSNameserversBulkPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPluginsNetboxDNSNameserversBulkPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPluginsNetboxDNSNameserversBulkPartialUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPluginsNetboxDNSNameserversBulkPartialUpdateOK creates a PluginsNetboxDNSNameserversBulkPartialUpdateOK with default headers values
func NewPluginsNetboxDNSNameserversBulkPartialUpdateOK() *PluginsNetboxDNSNameserversBulkPartialUpdateOK {
	return &PluginsNetboxDNSNameserversBulkPartialUpdateOK{}
}

/*
PluginsNetboxDNSNameserversBulkPartialUpdateOK describes a response with status code 200, with default header values.

PluginsNetboxDNSNameserversBulkPartialUpdateOK plugins netbox Dns nameservers bulk partial update o k
*/
type PluginsNetboxDNSNameserversBulkPartialUpdateOK struct {
	Payload *models.NameServer
}

// IsSuccess returns true when this plugins netbox Dns nameservers bulk partial update o k response has a 2xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this plugins netbox Dns nameservers bulk partial update o k response has a 3xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this plugins netbox Dns nameservers bulk partial update o k response has a 4xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this plugins netbox Dns nameservers bulk partial update o k response has a 5xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this plugins netbox Dns nameservers bulk partial update o k response a status code equal to that given
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the plugins netbox Dns nameservers bulk partial update o k response
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) Code() int {
	return 200
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/nameservers/][%d] pluginsNetboxDnsNameserversBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/nameservers/][%d] pluginsNetboxDnsNameserversBulkPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) GetPayload() *models.NameServer {
	return o.Payload
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NameServer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPluginsNetboxDNSNameserversBulkPartialUpdateDefault creates a PluginsNetboxDNSNameserversBulkPartialUpdateDefault with default headers values
func NewPluginsNetboxDNSNameserversBulkPartialUpdateDefault(code int) *PluginsNetboxDNSNameserversBulkPartialUpdateDefault {
	return &PluginsNetboxDNSNameserversBulkPartialUpdateDefault{
		_statusCode: code,
	}
}

/*
PluginsNetboxDNSNameserversBulkPartialUpdateDefault describes a response with status code -1, with default header values.

PluginsNetboxDNSNameserversBulkPartialUpdateDefault plugins netbox dns nameservers bulk partial update default
*/
type PluginsNetboxDNSNameserversBulkPartialUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this plugins netbox dns nameservers bulk partial update default response has a 2xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this plugins netbox dns nameservers bulk partial update default response has a 3xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this plugins netbox dns nameservers bulk partial update default response has a 4xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this plugins netbox dns nameservers bulk partial update default response has a 5xx status code
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this plugins netbox dns nameservers bulk partial update default response a status code equal to that given
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the plugins netbox dns nameservers bulk partial update default response
func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) Error() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/nameservers/][%d] plugins_netbox-dns_nameservers_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) String() string {
	return fmt.Sprintf("[PATCH /plugins/netbox-dns/nameservers/][%d] plugins_netbox-dns_nameservers_bulk_partial_update default  %+v", o._statusCode, o.Payload)
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *PluginsNetboxDNSNameserversBulkPartialUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
