// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPluginsNetboxDNSRecordsReadParams creates a new PluginsNetboxDNSRecordsReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPluginsNetboxDNSRecordsReadParams() *PluginsNetboxDNSRecordsReadParams {
	return &PluginsNetboxDNSRecordsReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPluginsNetboxDNSRecordsReadParamsWithTimeout creates a new PluginsNetboxDNSRecordsReadParams object
// with the ability to set a timeout on a request.
func NewPluginsNetboxDNSRecordsReadParamsWithTimeout(timeout time.Duration) *PluginsNetboxDNSRecordsReadParams {
	return &PluginsNetboxDNSRecordsReadParams{
		timeout: timeout,
	}
}

// NewPluginsNetboxDNSRecordsReadParamsWithContext creates a new PluginsNetboxDNSRecordsReadParams object
// with the ability to set a context for a request.
func NewPluginsNetboxDNSRecordsReadParamsWithContext(ctx context.Context) *PluginsNetboxDNSRecordsReadParams {
	return &PluginsNetboxDNSRecordsReadParams{
		Context: ctx,
	}
}

// NewPluginsNetboxDNSRecordsReadParamsWithHTTPClient creates a new PluginsNetboxDNSRecordsReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewPluginsNetboxDNSRecordsReadParamsWithHTTPClient(client *http.Client) *PluginsNetboxDNSRecordsReadParams {
	return &PluginsNetboxDNSRecordsReadParams{
		HTTPClient: client,
	}
}

/*
PluginsNetboxDNSRecordsReadParams contains all the parameters to send to the API endpoint

	for the plugins netbox dns records read operation.

	Typically these are written to a http.Request.
*/
type PluginsNetboxDNSRecordsReadParams struct {

	/* ID.

	   A unique integer value identifying this record.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the plugins netbox dns records read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSRecordsReadParams) WithDefaults() *PluginsNetboxDNSRecordsReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the plugins netbox dns records read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PluginsNetboxDNSRecordsReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) WithTimeout(timeout time.Duration) *PluginsNetboxDNSRecordsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) WithContext(ctx context.Context) *PluginsNetboxDNSRecordsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) WithHTTPClient(client *http.Client) *PluginsNetboxDNSRecordsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) WithID(id int64) *PluginsNetboxDNSRecordsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the plugins netbox dns records read params
func (o *PluginsNetboxDNSRecordsReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PluginsNetboxDNSRecordsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
